### ISSUE TITLE
$map: #007bff is not a map for `map-get'

### ISSUE THREAD

**Issue by a7madx7** [mkhairi/material-sass#5]
I can not start my server after adding your gem, for no reason what so ever, everything is working fine without it, as soon as I install it everything stops working and the error message tells me that I Can't use map-get ( in your css ) i.e. can't just execute the line:

@import "material";

**Comment by mkhairi** [comment]
hi @a7madx7, did you add ```@import "bootstrap"``` too in your application.scss?

**Comment by a7madx7** [comment]
Yeah, should I remove it?

**Comment by mkhairi** [comment]
@a7madx7, yeah.. you should remove it. this gem already serve the same thing like bootstrap. only bootstrap javascript is required.

**Comment by tatanpoker09** [comment]
I am running into the same issue. If I remove import bootstrap I get the problem in https://github.com/twbs/bootstrap/issues/23331 I am not using bootstrap through npm though. Only through ruby. I am working on Docker if that helps as info too
